nodes:
- input.visual:
    source: "edly_vid.mp4"
- model.yolo
- model.posenet
# - dabble.fps
- custom_nodes.dabble.joint_coordinates # --> we use this as reference
- draw.poses
# - draw.legend:
#     show: ["fps"]
- output.screen