nodes:
- input.visual:
    source: single_person.mp4
    #source: 0
- model.yolo
- model.posenet
- dabble.fps
#- custom_nodes.dabble.wave --> we use this as reference
- draw.poses
- draw.legend:
    show: ["fps"]
- output.screen